export enum IpcRendererMessage {
  ELECTRON_LLM_START_PROCESS = 'ELECTRON_LLM_START_PROCESS',
  ELECTRON_LLM_STOP_PROCESS = 'ELECTRON_LLM_STOP_PROCESS',
  ELECTRON_LLM_PROMPT = 'ELECTRON_LLM_PROMPT',
  ELECTRON_LLM_GET_CONVERSATION_HISTORY = 'ELECTRON_LLM_GET_CONVERSATION_HISTORY',
  ELECTRON_LLM_RESET_CONVERSATION_HISTORY = 'ELECTRON_LLM_RESET_CONVERSATION_HISTORY',
}
