export enum IpcRendererMessage {
  ELECTRON_LLM_CREATE = 'ELECTRON_LLM_CREATE',
  ELECTRON_LLM_DESTROY = 'ELECTRON_LLM_DESTROY',
  ELECTRON_LLM_PROMPT = 'ELECTRON_LLM_PROMPT',
  ELECTRON_LLM_PROMPT_STREAMING = 'ELECTRON_LLM_PROMPT_STREAMING',
}
